apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-ha.yaml
  - frontend-ha.yaml
  - ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: alphashopper
      app.kubernetes.io/managed-by: kustomize
