apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alphashopper-production

resources:
  - ../../base

patches:
  - path: patch-backend-externalsecret.yaml
    target:
      kind: ExternalSecret
      name: zigzag-backend-secrets
