apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alphashopper-production

resources:
  - ../../base

patches:
  - path: patch-servicemonitor-stable.yaml
    target:
      kind: ServiceMonitor
      name: zigzag-backend
  - path: patch-servicemonitor-canary.yaml
    target:
      kind: ServiceMonitor
      name: zigzag-backend-canary
  - path: patch-prometheus-rule.yaml
    target:
      kind: PrometheusRule
      name: alphashopper
