apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-servicemonitor.yaml
  - backend-canary-servicemonitor.yaml
  - prometheus-rule.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: alphashopper
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: monitoring
