apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alphashopper-production-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: alphashopper
  source:
    repoURL: https://github.com/khj874869/AlphaShopper.git
    targetRevision: main
    path: deploy/k8s/monitoring/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: alphashopper-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
