apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-canary.yaml
  - frontend-canary.yaml
  - backend-canary-ingress.yaml
  - frontend-canary-ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: alphashopper
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/track: canary
