apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-controller
  namespace: alphashopper
  labels:
    app.kubernetes.io/name: ingress-nginx-controller
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  endpoints:
    - port: prometheus
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: true
