apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alphashopper-staging-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: alphashopper
  source:
    repoURL: https://github.com/khj874869/AlphaShopper.git
    targetRevision: main
    path: deploy/argocd/apps/staging/children
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
