create table if not exists shop_member (
    id bigint generated by default as identity primary key,
    name varchar(50) not null,
    email varchar(100) not null,
    password varchar(100) not null,
    role varchar(20) not null,
    constraint uk_shop_member_email unique (email)
);

create table if not exists product (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    brand varchar(80) not null,
    price numeric(12, 2) not null,
    stock_quantity integer not null,
    description varchar(500) not null,
    image_url varchar(255),
    active boolean not null
);

create table if not exists coupon (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    name varchar(100) not null,
    discount_type varchar(30) not null,
    discount_value numeric(12, 2) not null,
    minimum_order_amount numeric(12, 2) not null,
    max_discount_amount numeric(12, 2),
    active boolean not null,
    expires_at timestamp not null,
    constraint uk_coupon_code unique (code)
);

create table if not exists shopping_cart (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    constraint uk_shopping_cart_member unique (member_id),
    constraint fk_shopping_cart_member foreign key (member_id) references shop_member (id)
);

create table if not exists purchase_order (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    status varchar(30) not null,
    total_amount numeric(12, 2) not null,
    discount_amount numeric(12, 2) not null,
    pay_amount numeric(12, 2) not null,
    shipping_address varchar(200) not null,
    coupon_code varchar(50),
    coupon_name varchar(100),
    delivery_status varchar(30) not null,
    tracking_number varchar(100),
    ordered_at timestamp not null,
    shipped_at timestamp,
    delivered_at timestamp,
    constraint fk_purchase_order_member foreign key (member_id) references shop_member (id)
);

create table if not exists cart_item (
    id bigint generated by default as identity primary key,
    cart_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    constraint fk_cart_item_cart foreign key (cart_id) references shopping_cart (id),
    constraint fk_cart_item_product foreign key (product_id) references product (id)
);

create table if not exists order_item (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    product_name varchar(120) not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    constraint fk_order_item_order foreign key (order_id) references purchase_order (id)
);

create table if not exists payment_transaction (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    method varchar(30) not null,
    status varchar(30) not null,
    amount numeric(12, 2) not null,
    transaction_key varchar(200),
    payment_reference varchar(100),
    requested_at timestamp not null,
    approved_at timestamp,
    refunded_at timestamp,
    failed_reason varchar(300),
    refund_reason varchar(300),
    constraint uk_payment_transaction_order unique (order_id),
    constraint fk_payment_transaction_order foreign key (order_id) references purchase_order (id)
);

create index if not exists idx_shopping_cart_member_id on shopping_cart (member_id);
create index if not exists idx_cart_item_cart_id on cart_item (cart_id);
create index if not exists idx_cart_item_product_id on cart_item (product_id);
create index if not exists idx_purchase_order_member_id on purchase_order (member_id);
create index if not exists idx_order_item_order_id on order_item (order_id);
create index if not exists idx_payment_transaction_reference on payment_transaction (payment_reference);
