create table if not exists kafka_dlt_replay_audit (
    id bigint generated by default as identity primary key,
    admin_member_id bigint not null,
    admin_email varchar(100) not null,
    admin_name varchar(50) not null,
    source_topic varchar(200) not null,
    target_topic varchar(200) not null,
    consumer_group_id varchar(200) not null,
    dry_run boolean not null,
    requested_messages integer not null,
    inspected_messages integer not null,
    replayed_messages integer not null,
    committed_messages integer not null,
    failed_messages integer not null,
    status varchar(30) not null,
    requested_at timestamp not null,
    completed_at timestamp,
    last_error varchar(500),
    constraint fk_kafka_dlt_replay_audit_admin foreign key (admin_member_id) references shop_member (id)
);

create index if not exists idx_kafka_dlt_replay_audit_requested_at on kafka_dlt_replay_audit (requested_at);
create index if not exists idx_kafka_dlt_replay_audit_admin_member_id on kafka_dlt_replay_audit (admin_member_id);
