create table if not exists ai_interaction_log (
    id bigint generated by default as identity primary key,
    member_id bigint,
    interaction_type varchar(30) not null,
    prompt varchar(1000) not null,
    reply varchar(2000),
    llm_used boolean not null,
    recommendation_count integer not null,
    recommended_product_ids varchar(500),
    requested_at timestamp not null,
    quality_score integer,
    quality_note varchar(500),
    reviewed_at timestamp,
    reviewed_by_member_id bigint,
    constraint fk_ai_interaction_log_member foreign key (member_id) references shop_member (id),
    constraint fk_ai_interaction_log_reviewer foreign key (reviewed_by_member_id) references shop_member (id),
    constraint ck_ai_interaction_log_quality_score check (quality_score is null or quality_score between 1 and 5)
);

create index if not exists idx_ai_interaction_log_requested_at on ai_interaction_log (requested_at);
create index if not exists idx_ai_interaction_log_member_id on ai_interaction_log (member_id);
create index if not exists idx_ai_interaction_log_type on ai_interaction_log (interaction_type);
