create table if not exists product_discovery_impression_log (
    id bigint generated by default as identity primary key,
    member_id bigint,
    surface varchar(40) not null,
    query_text varchar(1000) not null,
    product_id bigint not null,
    product_name varchar(120) not null,
    recommendation_source varchar(30),
    search_score real,
    rank_position integer not null,
    highlights varchar(1000),
    impression_key varchar(160),
    shown_at timestamp not null,
    constraint fk_product_discovery_impression_member foreign key (member_id) references shop_member (id),
    constraint fk_product_discovery_impression_product foreign key (product_id) references product (id),
    constraint ck_product_discovery_impression_rank check (rank_position >= 1)
);

create index if not exists idx_product_discovery_impression_shown_at
    on product_discovery_impression_log (shown_at);

create index if not exists idx_product_discovery_impression_member_id
    on product_discovery_impression_log (member_id);

create index if not exists idx_product_discovery_impression_surface
    on product_discovery_impression_log (surface);

create index if not exists idx_product_discovery_impression_product_id
    on product_discovery_impression_log (product_id);

create index if not exists idx_product_discovery_impression_source
    on product_discovery_impression_log (recommendation_source);
