apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigzag-backend-secrets
  namespace: alphashopper
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: alphashopper-secrets
  target:
    name: zigzag-backend-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: DB_URL
      remoteRef:
        key: alphashopper/shared/backend
        property: DB_URL
    - secretKey: DB_USERNAME
      remoteRef:
        key: alphashopper/shared/backend
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: alphashopper/shared/backend
        property: DB_PASSWORD
    - secretKey: APP_JWT_SECRET
      remoteRef:
        key: alphashopper/shared/backend
        property: APP_JWT_SECRET
    - secretKey: APP_PAYMENT_TOSS_SECRET_KEY
      remoteRef:
        key: alphashopper/shared/backend
        property: APP_PAYMENT_TOSS_SECRET_KEY
    - secretKey: APP_AI_LLM_API_KEY
      remoteRef:
        key: alphashopper/shared/backend
        property: APP_AI_LLM_API_KEY
    - secretKey: REDIS_HOST
      remoteRef:
        key: alphashopper/shared/backend
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: alphashopper/shared/backend
        property: REDIS_PORT
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: alphashopper/shared/backend
        property: REDIS_PASSWORD
    - secretKey: ELASTICSEARCH_URL
      remoteRef:
        key: alphashopper/shared/backend
        property: ELASTICSEARCH_URL
    - secretKey: KAFKA_BOOTSTRAP_SERVERS
      remoteRef:
        key: alphashopper/shared/backend
        property: KAFKA_BOOTSTRAP_SERVERS
    - secretKey: SMTP_HOST
      remoteRef:
        key: alphashopper/shared/backend
        property: SMTP_HOST
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: alphashopper/shared/backend
        property: SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: alphashopper/shared/backend
        property: SMTP_PASSWORD
